### ISSUE TITLE
Can't Scroll Content in Android Auto with MediaBrowserService

### ISSUE THREAD

**Issue by AndrewReitz** [androidx/media#2192]
### Version

Media3 main branch

### More version details

Reproduced on the latest release branch, but also able to reproduce using 1.5.1

### Devices that reproduce the issue

Phones:
Pixel 8
Pixel 4a
Samsung Galaxy 22

Android Auto:
Android Auto Desktop Head Unit

Have had users report this issue from actual cars to, but unable to verify what type of head units they are using.

### Reproducible in the demo app?

Yes

### Reproduction steps

Steps to reproduce:

- Install the demo-session app onto a phone that supports Android Auto
- Connect phone to Android Auto device 
- Launch the demo sessions app on Android Auto
- Play a song
- While playing the song tap Queue 
- Attempt to scroll the Queue

### Expected result

Queue should not jump to the top of the list, and should be able to scroll easily to the bottom.

### Actual result

Observe after about 5 seconds the queue will refresh and you'll be jumped to the top again.

This behavior is happening in all forms of scrolling in the Android Auto Browse interface, queue is just the easiest to navigate to.

Note: if music is paused, this issue does not occur.

### Media

Not applicable

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by AndrewReitz** [comment]
Email sent, includes video of the issue as well.

Occurs using Media 1.51, 1.4.1, and 1.3.1

**Comment by marcbaechinger** [comment]
Thanks for your report!

You are reporting `with MediaBrowserService`. The Media3 session demo app is using `MediaLibraryService` that is backwards compatible with `MediaBrowserService`. 

To rule out some sources of the problem:

> Have had users report this issue from actual cars to, but unable to verify what type of head units they are using.

* Can you confirm you are seeing this also with your app that it using `MediaBrowserService and not Media3 `MediaLibraryService`?

> Occurs using Media 1.51, 1.4.1, and 1.3.1

* I understand this started to fail for your app without you actually changing the app. Is this correct?
* You then tried to locate the problem by using the session demo for the versions you list above. Is this correct?

* Can you please report the version of the Android Auto companion app that is running on the devices you tested with?

Sorry for all these questions. I'm asking because there was a change in the AA app.  Knowing the exact source of error allows to find the best fix and to see whether Media3 can do something to counter act future problems of this sort. It can also be that Media3 is behaving in a way that isn't right.

**Comment by marcbaechinger** [comment]
The screencast seems to indicate that this does not only happen for the queue but also when a category of items is displayed that is pulled by the app from the service (in contrast to the queue/timeline for which the session can push a change). 

From the logs I see these lines of output around '4:09' which is the time displayed on the device screen in the screen cast. The 3 second interval these error lines are printed to logcat, may match to the time in the screen cast until the item list is reset to the first item after scrolling.  

I'm trying to get some looking into it who is familiar with how this behaves. Still useful to know the AA companion app version in case you can get this.

```
02-26 16:09:36.919 10263 23435 23435 D EventLogger: playWhenReady [eventTime=1859.56, mediaPos=11.10, window=0, period=0, true, USER_REQUEST]
02-26 16:09:36.926 10263 23435 23435 D EventLogger: isPlaying [eventTime=1859.57, mediaPos=11.10, window=0, period=0, true]
02-26 16:09:52.030 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:09:52.030 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:09:53.611 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:09:53.611 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:09:53.863 10263 23435 23435 D EventLogger: loading [eventTime=1876.51, mediaPos=28.62, window=0, period=0, true]
02-26 16:09:53.954 10263 23435 23435 D EventLogger: loading [eventTime=1876.60, mediaPos=28.71, window=0, period=0, false]
02-26 16:09:57.302 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:09:57.302 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:00.007 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:00.007 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:03.033 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:03.033 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:03.817 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:03.817 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:06.042 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:06.043 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:08.204 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:08.204 10153  8680  8680 E CarApp.H.Per: Timer was started while already running! GEARHEAD_CAL_SET_TEMPLATE_NEW_PRESENTER
02-26 16:10:09.266 10263 23435 23435 D EventLogger: playWhenReady [eventTime=1891.91, mediaPos=44.01, window=0, period=0, false, USER_REQUEST]
02-26 16:10:09.278 10263 23435 23435 D EventLogger: isPlaying [eventTime=1891.92, mediaPos=44.01, window=0, period=0, false]
```

**Comment by AndrewReitz** [comment]
> Sorry for all these questions.

No worries, I've been trying to debug this all week and I know how important getting answers is. I am leaning towards this being the AA app. I tried the demo app out on [head unit reloaded](https://play.google.com/store/apps/details?id=gb.xxy.hr) and didn't see the issue. And a user reported this on a 2023 Honda CRV Hybrid Sport if that helps at all. Here's the source of my [app](https://github.com/Ghost-Applications/gizz-tapes) that I'm seeing the issue on if that helps at all.

> You are reporting with MediaBrowserService. The Media3 session demo app is using MediaLibraryService that is backwards compatible with MediaBrowserService.

Yeah, sorry, I grabbed that from the manifest, I'm using MediaBrowserService.

> I understand this started to fail for your app without you actually changing the app. Is this correct?

I was changing the app and started noticing this issue. I thought it was my change at first, but after testing the demo app I noticed it was occurring there too. When I was filing the bug report I started using older version to hopefully pinpoint a version where this started happening.

> You then tried to locate the problem by using the session demo for the versions you list above. Is this correct?

This was on the [gizz tapes app](https://github.com/Ghost-Applications/gizz-tapes).

> Can you please report the version of the Android Auto companion app that is running on the devices you tested with?

On my Pixel 4a:
13.7.650624-release

On my Galaxy 22:
13.5.6502483-release

Let me know if I can provide any more info!

**Comment by albinus-sc** [comment]
Assuming these are the same issues, here's some additional info:

This happens on our own app, but also on Spotify (but only when listening to podcasts, not music).

I've found a few other reports about this:
https://support.google.com/androidauto/thread/323813672/android-auto-media-app-scrolling-bugs
https://www.reddit.com/r/AndroidAuto/comments/1ikjozo/podcast_addict_playlist_scrolling/

I'm guessing a new version of Android Auto broke something, rendering media apps relatively useless as you can only scroll if you stop playback.

I also don't see progress bars on media items that I've listened to partially or completely, on our own app or Spotify. So that's great 🙃

**Comment by rolandvar** [comment]
I am experiencing the same problem.
In my music playback app it happens only when the player is playing, while, using spotify it happens only if I listen to podcasts.
My version of Android Auto is:
- 13.7.650624-release 
My device is:
- Redmi 12 Pro 5G Android 12 SP1A.210812.016

These are the dependencies of media3 in my application:
```
    implementation(“androidx.media3:media3-exoplayer:1.5.1”)
    implementation(“androidx.media3:media3-session:1.5.1”)
    implementation(“androidx.media3:media3-ui:1.5.1”)
    implementation(“androidx.media3:media3-exoplayer-hls:1.5.1”)
    implementation(“androidx.media3:media3-exoplayer-dash:1.5.1”)
    implementation(“androidx.media3:media3-exoplayer-smoothstreaming:1.5.1”)
    implementation(“androidx.media3:media3-common:1.5.1”)
```

If it is helpful I can attach a logcat.

**Comment by Tomil740Gini** [comment]
Confirmed with Media3 version 1.4.1. We are also experiencing the auto-scroll-to-top bug on Android Auto during active playback, which severely impacts the user experience. This appears to be a platform-level issue, and we will be tracking this thread.

**Comment by marcbaechinger** [comment]
The problem was reported for these versions here in this thread:

* 13.7.650624-release
* 13.5.6502483-release

As far as I can tell there is already a version 14.x.yyyyy released. In the playstore app the most recent version seems to be `14.7.65284-release` On my own phone I'm on a beta program and I have a Android Auto version of `15.x.yyy`.

If you see this problem and specifically when you report the problem here, please let us know the version number of the Android Auto app for which you are seeing this behavior. My assumption is that this is fixed on 14.xx or at least the version on the playstore, so basically an update of the companion app would be expected to fix the problem. 

Please note that on devices with a faulty AA version like 13.7.650624-release, the Media3 library can't fix something as the UI behavior is part of the Android Auto app, not Media3.

**Comment by banksio** [comment]
I'm still seeing this behaviour on Android Auto `16.6.661444-release`.

**Comment by marcbaechinger** [comment]
This is reported as fixed internally. Can you expand on "this behavior"?

People who  reported this earlier up here in this bug, do you still see this?

**Comment by banksio** [comment]
Of course. By _this behaviour_, I mean the following:

Whilst a song is playing, the queue view in Android Auto appears to refresh/reload every few seconds. That means that if you scroll down in the queue, you are forced back up to the top, essentially making the queue view useless as you are unable to select a song near the bottom. Other views seem unaffected.

Disabling periodic updates to mitigate this bug doesn't appear to affect the functionality of the app otherwise.

The issue is visible in the PR branch of Gramophone that I referenced above, if you comment out the disable periodic updates workaround. Happy to provide a screen recording of the issue on the desktop head unit or my own vehicle if that's helpful.

**Comment by marcbaechinger** [comment]
Thanks for the details. Very useful.

If you can do a screencast that be great. I assume this is for `16.6.661444-release` , else please mention the version you used with the device on the screencast.

I can then look into this with our demo app so I can give the Auto team clear instructions with an app they can easily deploy.

**Comment by banksio** [comment]
Hi Marc, yes it's for version `16.6.661444-release`. I've actually used the media3 session demo app hopefully to make your life easier with reproducing the bug!

There's no audio on the below video, but the music was playing fine. I start a moderate sized queue from the app on the phone (though it will also happen if started from the head unit), and then observe the behaviour of the queue on Android Auto. As you can see, when I try to scroll down, the queue keeps refreshing, causing it to lose the scroll state and go back to the top repeatedly.

This is the same behaviour I was getting with Gramophone, without the workaround; adding `.setPeriodicPositionUpdateEnabled(false)` will stop this from happening, but I don't know if that may disable some other functionality.

https://github.com/user-attachments/assets/2bf28500-69ed-41f6-ba36-d751f343caab

**Comment by NEVARLeVrai** [comment]
https://github.com/user-attachments/assets/a833d387-8526-48fd-a096-aabfe6813541

still facing this in 2026 on my app

**Comment by NEVARLeVrai** [comment]
> Hi Marc, yes it's for version `16.6.661444-release`. I've actually used the media3 session demo app hopefully to make your life easier with reproducing the bug!
> 
> There's no audio on the below video, but the music was playing fine. I start a moderate sized queue from the app on the phone (though it will also happen if started from the head unit), and then observe the behaviour of the queue on Android Auto. As you can see, when I try to scroll down, the queue keeps refreshing, causing it to lose the scroll state and go back to the top repeatedly.
> 
> This is the same behaviour I was getting with Gramophone, without the workaround; adding `.setPeriodicPositionUpdateEnabled(false)` will stop this from happening, but I don't know if that may disable some other functionality.
> 
>  out.mp4

thx for the .setPeriodicPositionUpdateEnabled(false) actually worked !, didnt read your post correctly
