### ISSUE TITLE
Pressing Play/Pause button twice on remote devices triggers Command_Seek_To_Next

### ISSUE THREAD

**Issue by charlesEnigma** [androidx/media#962]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Fire Tv Stick 4k Max (2nd Gen) running Fire OS 8.1.0.2 = Android 11 
Sony Bravia A95L running Android 12
Sony Bravia A95K running Android 11

### Devices that do not reproduce the issue

Devices without Play/Pause button

### Reproducible in the demo app?

No

### Reproduction steps

Issue is the same as this issue: https://github.com/androidx/media/issues/233

We're seeing the issue on devices with a Play/Pause button on their remote. The issue is pressing the Play/Pause twice is triggering the COMMAND_SEEK_TO_NEXT command inside Media3 MediaSession. Originally we created a workaround for this issue since this was a known bug: [androidx/media#233](https://github.com/androidx/media/issues/233). Our workaround is causing an issue on FireTV for the Next voice command so we are removing the workaround but notice this issue persists.

Our app is using Media3 version 1.1.1.

Any suggestions on how to prevent MediaSession from triggering COMMAND_SEEK_TO_NEXT when Play/Pause button is pressed twice?

### Expected result

Pressing Play/Pause multiple times plays or pauses playback.

### Actual result

The next episode command is triggered. 

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by charlesEnigma** [comment]
Closing ticket. This issue is resolved with 1.2.0

**Comment by charlesEnigma** [comment]
This appears to be fixed for Fire TV devices using Media3 v1.2.0. I'm still seeing the issue on Android TV devices such as Sony Bravia A95L.

**Comment by charlesEnigma** [comment]
Sorry, for the confusion. When updating to version 1.2.0 our workaround was re-enabled so it appeared to be fixed but after removing the workaround we are seeing the issue in version 1.2.0 as well.

**Comment by tianyif** [comment]
Hi @charlesEnigma,

Starting from 1.2.0, [`MediaSession.Callback.onMediaButtonEvent`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L1470) has been added so you can override the default implementation and handle media buttons in a custom way. Could you please try this and see if it can solve your problem?

**Comment by tianyif** [comment]
I'm re-tagging it as "bug" as we should figure out why the remote device doesn't resolve the double tap as next, because if it does, the remote device can define the behaviour of the tapping rather than the library or apps.

**Comment by marcbaechinger** [comment]
I think the issue is related to TV remotes that sends key events over Bluetooth. This may be a [GoogleTV remote](https://store.google.com/ie/product/chromecast_google_tv_voice_remote?hl=en-GB&pli=1) or a generic [D-pad TV remote](https://www.amazon.co.uk/Replacement-KD-49XE8004-KD-49XE8005-KD-43XF8096-KD-43XF8505/dp/B0BGH8W8GP/ref=asc_df_B0BGH8W8GP/?tag=googshopuk-21&linkCode=df0&hvadid=606775922780&hvpos=&hvnetw=g&hvrand=1181964432146274334&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9045997&hvtargid=pla-1944282363026&psc=1&mcid=80fd9335fa58368bb6957e0e2d640a5c) like for instance for a Sony Bravia.

The double-click detection seems to be most useful on mobile devices when a user has connected a BT headset to the device. I think it justifiable to simply disable double-click detection on TV devices.

@charlesEnigma Any thoughts whether this would help for your case?

**Comment by charlesEnigma** [comment]
@tianyif, 

I will try overriding [MediaSession.Callback.onMediaButtonEvent](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L1470)  and see if we can handle the media buttons in a custom way. 

@marcbaechinger, 
Yes, disabling double-click detection on TV devices would help our use case. By disabling double-click detection on TV devices we would simply be preventing the users from rapidly pressing buttons correct? For example, the user presses the "play/pause" button waits at least 2 seconds, and presses the "play/pause" button again triggering the "play/pause" functionality.

**Comment by marcbaechinger** [comment]
> By disabling double-click detection on TV devices we would simply be preventing the users from rapidly pressing buttons correct?

The library doesn't swallow events. All events will be delivered but the events won't be translated to a skip next event but the events arrive at the player resulting in pausing then playing again which is what the user intended to do with pressing twice.

**Comment by marcbaechinger** [comment]
I'm closing this issue as it is fixed with the commit above. Please open a new issue if required.

**Comment by charlesEnigma** [comment]
@tianyif and @marcbaechinger , 

I was able to override KEYCODE_MEDIA_PLAY_PAUSE using [MediaSession.Callback.onMediaButtonEvent]. 

`
override fun onMediaButtonEvent(
            session: MediaSession,
            controllerInfo: MediaSession.ControllerInfo,
            intent: Intent
        ): Boolean {

            val keyEvent: KeyEvent? = intent.getParcelableExtra<KeyEvent>(Intent.EXTRA_KEY_EVENT)
            val keyCode = keyEvent?.keyCode
            when (keyCode) {
                KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE  -> {
                    if(keyEvent.action == KeyEvent.ACTION_UP) {
                        if (session.player.playWhenReady) {
                            session.player.pause()
                        } else {
                            session.player.play()
                        }
                    }
                    return true
                }
                else ->  return super.onMediaButtonEvent(session, controllerInfo, intent)
            }
        }
`

Questions: 

1.  Disable double-click detection on TV devices is this something the developer is expected to implement or will this be included in future versions of media3?

**Comment by marcbaechinger** [comment]
The [commit referenced above](https://github.com/androidx/media/commit/2c8ba50524ac47cf2587e7d0110e427be0806478) implements this and this will be part of the next release.

**Comment by charlesEnigma** [comment]
@marcbaechinger, 

Awesome and thank you. The team will be looking forward to the next release. :-)
